version: '3.9'

services:
  tika:
    image: apache/tika:latest
    container_name: tika
    restart: on-failure
    ports:
      - "9998:9998"
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: on-failure
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j_data/data:/data
      - ./neo4j_data/logs:/logs
      - ./neo4j_data/import:/import
      - ./neo4j_data/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
volumes:
  data: